### ISSUE TITLE
Error in run.sh

### ISSUE THREAD

**Issue by dry** [230delphi/hassio-addons#1]
Hi,

After running addon I keep seeing this error. Can you help me figure out what the cause might be?

![image](https://user-images.githubusercontent.com/342807/140610138-06ad4b13-e744-4190-ad65-91818fe8dce2.png)

**Comment by 230delphi** [comment]
not seen that before - what platform are you running on? Pi?

**Comment by dry** [comment]
Yep, a Pi. HA OS. Supervisor, Core and OS all up to date.

**Comment by 230delphi** [comment]
testing now on a similar fresh install - main system is intel.

**Comment by 230delphi** [comment]
ok, reproduced it. The problem in the underlying flogger library regarding support for arm processors (which don't have the syscall.Dup2).
I'll investigate for workarounds.

**Comment by dry** [comment]
Ah, okay. Thanks very much for taking a look at this.

**Comment by 230delphi** [comment]
I'm going to replace that logger library will let you know how it goes!

**Comment by 230delphi** [comment]
moved to another logger, now compiles ok on pi, but I haven't done a full check. 
full test on intel looks ok. let me know how it goes.

**Comment by dry** [comment]
It now builds correctly and has started properly according to the logs. Thank you very much. I have a question about how to integrate this properly. According to your docs, it looks very much like you are using a Linux box as your primary router. Is that right?

**Comment by 230delphi** [comment]
yes - on the alpha: I configured the default gateway as my linux box.
and yes, i need to improve the docs :/

**Comment by dry** [comment]
Ah, okay. So, that means I'd need my installer pasword? I'll have to have a think about how I can force that traffic to the Pi. I do really want to see all those different sensors you've enabled :)

**Comment by dry** [comment]
I can connect to the 10.10.10.1 status page i.e. where you can do firmware updates etc. Did you just change the Gateway IP there to be your Linux box and then use the iptables rule to then forward that traffic to your HA instance?

**Comment by 230delphi** [comment]
exactly.. although I used the physical LED interface on the device rather
than any status page?

**Comment by 230delphi** [comment]
fixed by updating logger
