### ISSUE TITLE
Error: s6-overlay-suexec: can only run as pid 1

### ISSUE THREAD

**Issue by tbgoose** [230delphi/hassio-addons#4]
Hi 

I am having the following error when starting the addon. I don't think I have done my config correctly to be honest. I can't see anywhere on the alpha portal to be able to change destination of battery reporting to my HA instance (192.168.1.204).

`s6-overlay-suexec: fatal: can only run as pid 1`

Here is my config
AlphaESSID: _Alpha Serial Number_
MQTTTopicBase: homeassistant/sensor/
TZLocation: Australia/Brisbane
ProxyIPPort: 0.0.0.0:27777
MSGLogging: ''
LogLevel: 1
MQTTAddress: tcp://127.0.0.1:1883
MQTTUser: _xxx_
MQTTPassword: _xxx_
DestinationIpPort: 52.230.104.147:7777

I haven't done the router iptables thing yet, as I haven't managed to start the addon. I have an edgerouter x so shouldn't be an issue using your example command `sudo iptables -t nat -D PREROUTING -p tcp --dport 7777 -j DNAT --to 192.168.1.204:27777`

**Comment by wfa001** [comment]
confirm: i get the same error message when trying to start the addon.

**Comment by mrrodge2020** [comment]
+1 - Same issue.  Very keen to get this working!

**Comment by 230delphi** [comment]
Thanks for the poke on this one. I've been running on an Intel nuc with no problems for the last 2ish years.
please retest - I've updated per https://github.com/230delphi/hassio-addons/commit/0258828f45e69f0c8976d83ca26c2c44577f4135

**Comment by mrrodge2020** [comment]
Amazing - thanks!  Will try ASAP.

**Comment by mrrodge2020** [comment]
Trying to set this up now - was going the direct connection route but my SMILE5 inverter won't let me change the target server in the network settings, so it looks like transparent is my only option.

**Comment by 230delphi** [comment]
resolved
